# Generated by Django 3.0.6 on 2020-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_code', models.CharField(max_length=20)),
                ('referal_code', models.CharField(max_length=20)),
                ('hosted_by', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('event_status', models.DecimalField(decimal_places=0, max_digits=2)),
                ('winner', models.CharField(max_length=100)),
                ('starting_date', models.DateTimeField()),
            ],
        ),
    ]
