# Generated by Django 3.0.6 on 2020-05-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='ending_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='starting_date',
            field=models.DateTimeField(default=None),
        ),
    ]
