# Generated by Django 3.0.6 on 2020-05-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_auto_20200525_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('event_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.Events')),
            ],
        ),
    ]
