# Generated by Django 3.0.6 on 2020-05-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_status',
            field=models.IntegerField(default=0),
        ),
    ]
