# Generated by Django 3.0.6 on 2020-05-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0006_auto_20200528_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='winner',
        ),
    ]
