# Generated by Django 3.0.6 on 2020-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0007_remove_events_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='hosted_by',
            field=models.CharField(max_length=100),
        ),
    ]
