# Generated by Django 3.0.6 on 2020-06-01 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting_app', '0009_auto_20200530_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_time', models.DateTimeField(auto_now_add=True)),
                ('option_name', models.CharField(max_length=150)),
                ('event_code', models.CharField(max_length=70)),
                ('referal_code', models.CharField(max_length=70)),
                ('voter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
