# Generated by Django 3.0.6 on 2020-06-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0010_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='event_name',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
