# Generated by Django 4.2 on 2023-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0012_auto_20200601_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='ending_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='starting_date',
            field=models.DateField(default=None),
        ),
    ]
